//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.29 at 07:06:52 PM EET 
//


package service.endpointrequestresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import service.dto.DBUserDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBUserDTO" type="{http://www.dto.service/}DBUserDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbUserDTO"
})
@XmlRootElement(name = "CreateDBUserRequest")
public class CreateDBUserRequest {

    @XmlElement(name = "DBUserDTO", required = true)
    protected DBUserDTO dbUserDTO;

    /**
     * Gets the value of the dbUserDTO property.
     * 
     * @return
     *     possible object is
     *     {@link DBUserDTO }
     *     
     */
    public DBUserDTO getDBUserDTO() {
        return dbUserDTO;
    }

    /**
     * Sets the value of the dbUserDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBUserDTO }
     *     
     */
    public void setDBUserDTO(DBUserDTO value) {
        this.dbUserDTO = value;
    }

}
