//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.29 at 07:06:52 PM EET 
//


package service.endpointrequestresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import service.dto.UpdateDBUserDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBUser" type="{http://www.dto.service/}UpdateDBUserDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbUser"
})
@XmlRootElement(name = "UpdateDBUserRequest")
public class UpdateDBUserRequest {

    @XmlElement(name = "DBUser", required = true)
    protected UpdateDBUserDTO dbUser;

    /**
     * Gets the value of the dbUser property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateDBUserDTO }
     *     
     */
    public UpdateDBUserDTO getDBUser() {
        return dbUser;
    }

    /**
     * Sets the value of the dbUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateDBUserDTO }
     *     
     */
    public void setDBUser(UpdateDBUserDTO value) {
        this.dbUser = value;
    }

}
